### ISSUE TITLE
Travis CI test fails mysteriously on the invalid command test

### ISSUE THREAD

**Issue by anko** [anko/tests-ex-markdown#1]
[This test](https://github.com/anko/tests-ex-markdown/blob/ca60837cbddf5a2f13a650a953e6b0e9eb86b998/test.ls#L386-L432) (which checks that stderr output from tests-ex-markdown includes shell errors) works on my machine, but the tests-ex-markdown process [dies on Travis](https://travis-ci.org/anko/tests-ex-markdown/builds/232161360), [more specifically](https://travis-ci.org/anko/tests-ex-markdown/jobs/232161368#L332-L340) by throwing EPIPE:

```
not ok 38 stderr matches
  ---
    operator: equal
    expected: |-
      'Command failed: invalidcommand12341234\n/bin/sh: invalidcommand12341234: command not found\n\n'
    actual: |-
      'events.js:163\n      throw er; // Unhandled \'error\' event\n      ^\n\nError: write EPIPE\n    at exports._errnoException (util.js:1050:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:814:14)\n'
    at: Test.<anonymous> (/home/travis/build/anko/tests-ex-markdown/test.ls:38:9)
  ...
```

EPIPE only happens when attempting to write to a file descriptor which is closed.

Even more mysteriously, the stack trace points to it failing at this line of test code:

```js
t.equals(stderr.toString(), expected.stderr, "stderr matches");
```

This makes _zero sense_ to me. Converting a buffer to a string has nothing to do with pipes, never mind the narrower case of writing to a pipe after it closes.

What's going on?

Given I can't repro this locally, I've been pushing attempts to the branch [`alternative-stderr-test`](https://github.com/anko/tests-ex-markdown/tree/alternative-stderr-test) trying to get Travis to see sense, but with no effect yet.

**Comment by anko** [comment]
The test was changed in https://github.com/anko/tests-ex-markdown/commit/cf7fe797f5168a95afc81ed5dc08ec8ea0686bed, and [Travis passes without errors](https://travis-ci.org/github/anko/tests-ex-markdown/builds/662745830). Whatever the heck this was, it is no longer.
